DEL=*~ .*.sw*
FTP_FILES=admin.css dbobject.inc.php menuText.php page.inc.php utilisateur.inc.php admin_menu.inc.php index.inc.php menu.php message.inc.php pied.php css.inc.php menu_png.php nouvelle.inc.php resa.inc.php
FTP_REP_DEST=/includes/

clean: 
	rm -f $(DEL)

include ../../../Makefile.ftp
